README.md
extension/index.js
extension/manifest.json

Thanks to https://developer.chrome.com/extensions/xhr

Use github and npm directly

---

extension/index.js

show dependency version info

---

extension/index.js

Closes https://github.com/npmhub/npmhub/issues/24
Closes https://github.com/npmhub/npmhub/issues/18

Added support for monorepos

---

.gitignore
.travis.yml
extension/manifest.json
package.json

Get extension version from git tag

---

README.md

https://github.com/BrainMaestro/packagehub
http://ghub.io/
cc @BrainMaestro

mention related projects in the readme

---

extension/index.js

😔 Is it an error? Is it a plane? Is it a hot dog?
😎 Ah, it's a good thing!

Celebrate dependency-free packages

---

extension/index.css

Add CSS loading animation

---

extension/background-fetch.js
extension/index.js
package.json

npmhub already matched xo's style (except the spaces instead of tabs) so I figured I'd just use that to validate it.

Add JavaScript style tests via xo

---

README.md
extension/manifest.json
extension/options.html
package.json
rollup.config.js
src/background.js
src/index.js
src/options.js

Add support for GitHub/GitLab Enterprise via options

---

src/content.js

Restore GitLab support

---

src/content.js

Example: https://github.com/sindresorhus/refined-github

Avoid errors on nameless packages

---

src/content.js

Fix support for bundledDependencies

---

src/content.js

Use <g-emoji> for compatibility

---

package-lock.json
package.json
src/content.js

Fixes #74 
Tested on:
* https://gitlab.com/Rich-Harris/buble/tree/master
* https://gitlab.com/Rich-Harris/buble/blob/master/package.json
* https://github.com/Rich-Harris/buble
* https://github.com/Rich-Harris/buble/blob/master/package.json
And also on a private GH repo

Show also on package.json pages

---

src/content.js

Mark 404s and network failures

---

src/content.js

I think this is a much stronger visualization.
Compare http://npm.anvaka.com/#/view/2d/lighthouse vs http://npm.broofa.com/?q=lighthouse

Switch module tree viz force-directed graph -> dotviz

---

source/content.css
source/content.js

Make buttons more compact

---

package.json
source/background.js
source/content.js
source/lib/parse-repo-url.js
source/lib/reduced-url.js

fixes #92 
Now it works like a charm again.
cc @bfred-it

Avoid CORB introduced in Chrome 73

---

source/background.js
source/content.js

Since we have to fetch packages in background.js, we can have a global in-memory cache.
Every 12 hours it gets trimmed to the latest 1000 packages.

Add LRU cache

---

source/components/App.svelte

Supersedes and closes #133
I have tested all the links once again with https://github.com/sindresorhus/delay. All links return `HTTP 200` on the first HTTP request.

Avoid redirects in links

---

source/components/App.svelte
source/components/Box.svelte

- Fixes https://github.com/npmhub/npmhub/issues/147

Fix sticky header overlap

---

package.json
source/components/App.svelte

Fix alignment

---

source/manifest.json

Fully drop GitLab references

---

package-lock.json
package.json
source/npmhub.js

- See https://github.com/refined-github/refined-github/issues/5719
https://user-images.githubusercontent.com/1402241/201596571-40e5caa4-bd03-45d1-b82d-5f761b171ebb.mov

Show npmhub without having to refresh the page (ajax issue)

---

source/components/App.svelte

- Closes https://github.com/npmhub/npmhub/pull/164

Restore Firefox support

---

source/components/App.svelte

- Closes https://github.com/npmhub/npmhub/issues/131

Add Types link (paka.dev)

---

source/npmhub.js

Restore support for file lists

---

.eslintrc
.github/workflows/release.yml
.github/workflows/test.yml
.parcelrc
package-lock.json
package.json
source/components/App.svelte
source/components/Box.svelte

Stole some logic from https://github.com/hankxdev/one-click-extensions-manager/pull/125

Update all dependencies

---

source/components/App.svelte
source/components/HeaderLinkNpmGraph.svelte

- Closes https://github.com/npmhub/npmhub/issues/132
- Kinda blocked by https://github.com/npmgraph/npmgraph/pull/193

Link to "Dependency tree" even on unpublished packages

---

source/components/App.svelte

https://x.com/aboodman/status/1745544048860127613

Drop "Types" link (paka.dev is down)
