index.js

https://github.com/zeke/npm-hub/pull/7#issuecomment-222343707
I also made a change to simplify the style application. I would have used template literals but they're not supported in Safari 8
The 13px style matches the file list above the readme

Style fix as requested

---

extension/index.js

[anvaka/npmgraph.an](https://github.com/anvaka/npmgraph.an) provides a nice visualization of the entire dep tree.
This PR adds a button into the injected DOM so you can easily click to view this tree:

Add button to launch visualization of entire module dependency tree

---

extension/index.js

Thanks for the excellent extension @zeke and @bfred-it!
Took a stab at adding support for private repos, since I use them on a day-to-day basis. I initially was going to make a request to `https://github.com/user/repo/raw/master/package.json`, but it 301s to a host that isn't allowed by the content security policy on the page.
I needed to move the request from the background page to the content script, because the current session cookie needs to be sent with the request for auth w/ private repositories.

Add support for private repos

---

extension/index.js

This PR removes the semver range from the dependency list, because it's not really a helpful thing to see. Name, description, and hyperlink are what matter most. Users can easily view the `package.json` to check semver ranges for all dependencies.

remove semver range from output

---

extension/index.js

Sometimes, we tend to define our [dev]dependencies as empty objects as an indication of dependency-free package. This commit added support for showing the `empty` message when one of the dependencies and devDependencies is empty.

Show `empty` message when dependencies are empty

---

extension/index.js

This PR updates the links to always point to ghub.io instead of npmjs.com.
The npm website hasn't changed in years. GitHub is a better place to go to find out what's up with a package.. is it alive? how many maintainers does it have? Does it have tests? etc..
For packages that don't have a GitHub repository, ghub.io redirects to the npmjs.com package page.

Always use ghub.io

---

extension/index.js
extension/manifest.json

As talked about in #32, this PR adds GitLab support.
For now it only supports gitlab.com but once #31 merged, it should also support private gitlab instances.

GitLab support

---

extension/index.js

1. Code streamlined.
2. This will only leave one box saying “No dependencies” instead of two. Example: https://github.com/bfred-it/random-encoder
* Based on no-anvaka branch

Only one empty list

---

extension/index.js

Anvaka doesn’t display dev dependencies.
Try it out on [npmhub's own repo](https://github.com/npmhub/npmhub)

Hide anvaka button when there are no dependencies

---

extension/index.js

This is consistent with the rest of GitHub's own buttons

Update anvaka button label

---

extension/manifest.json

There’s no need to have the extension’s background page run constantly in the background, so make it launch on demand to save RAM.
https://developer.chrome.com/extensions/event_pages

Use event pages instead of staying in background persistently

---

extension/index.css
extension/index.js

Some packages don't link to the npmjs page, so it'd be nice to have a button that is consistently available. Also it wouldn't be terrible to add a few further npm-related features.

Add `Open on npmjs.com` button

---

src/content.js

If you load a repo's homepage and then quickly change to Pull requests, in-flight Fetches might complete after the page change and append the Dev Dependencies to the Pull request page ![](http://i.imgur.com/H9l2rvg.png)
Untested

Ensure that they are all attached to the same container

---

.travis.yml
package.json

https://github.com/bfred-it/daily-version
Let's wait a day before merging this. The first version generated by `daily-version` has to be higher than the current one, but `daily-version` doesn't know what the current version is until its second run.

Shorten version with bfred-it/daily-version

---

src/content.js

Since #77, `ghub.io` doesn't add anything to npmhub since it supports a lower number of `repository` formats.
It's best to just link to `npmjs.org` so if dependencies are 404s (#79) the user will be linked to the official 404 page.

By default, link to npm, not ghub.io

---

src/lib/parse-repo-url.js

Example repo with dependency: https://github.com/babel/babel/tree/master/packages/babel-plugin-syntax-object-rest-spread
Example of repository field value: https://github.com/babel/babel/blob/f76ac0b/packages/babel-core/package.json#L9

Fix support for custom repo URLs

---

extension/content.css

Visually separate private/failed repos

---

source/components/Box.svelte

Currently, npmhub will render "undefined" if package.json does not contain a description field.
This PR fix the behaviour by rendering an empty string instead of "undefined".

Don't show `undefined` if a description is missing

---

README.md

Hi @fregante! I noticed the README says:
>If you love Refined GitHub, consider sponsoring ...
But this project isn't Refined GitHub, so I was thinking that that's a copy/paste error.

Fix copy-paste error in readme

---

INSTALLED.md

INSTALLED.md reads
> For a good example, check out these two dependency lists:
To maintain that claim correctly, I have added another URL to the list.
I understand that this was previously used to demonstrate how the extension works on both GitHub and GitLab.
This could also be changed as follows too :
```diff
-There's nothing to configure. Just surf around on GitHub and whenever you're viewing a repo with npm dependencies, you'll see them listed below the README. For a good example, check out these two dependency lists:
-
-- [**github.com**/sindresorhus/delay#dependencies](https://github.com/sindresorhus/delay#dependencies)
-- [**github.com**/sindresorhus/refined-github#dependencies](https://github.com/sindresorhus/refined-github#dependencies)
+There's nothing to configure. Just surf …
```

Meta: Add one more example URL to the docs

---

source/components/App.svelte
source/components/Box.svelte

Update HTML ID for the dependencies table for easy reach
This was missed when re-writing with svelte ( https://github.com/npmhub/npmhub/pull/136#issuecomment-909034295 )

Add `#dependencies` deeplink for npmhub

---

source/components/Box.svelte

Updates class name to match github's.
Fixes the following:

Fix: Missing background in Box header

---

.terserrc
package.json

See:
- https://github.com/fregante/GhostText/pull/207
- https://github.com/parcel-bundler/parcel/issues/6092
Due to:
> 
> Hi there,
> 
> We regret to inform you that the most recent submission of your item was rejected. Please find the details below.
> 
> 
> Item name: npmhub
> 
> Item ID: kbbbjimdjbjclaebffknlabpogocablj
> 
> Violation(s):
> 
> Code Readability Requirements
> 
> Violation reference ID: Red Titanium
> Violation: Having obfuscated code in the package.
> Violating content:
> Code snippet: background.js:null:null: const $f1fa3f598bcb30fb$var$m..............
> Code snippet: npmhub.js:null:null: var $f2f31784991bc.................................
> How to rectify: Replace the obfuscated code with human-readable code and resubmit the item.
> Relevant section of the program …

Meta: Improve the bundle

---

CONTRIBUTING.md
source/components/App.svelte
source/components/Box.svelte
source/npmhub.js

Replaces and closes https://github.com/npmhub/npmhub/pull/157
It triggers a request on every page with `package.json`, but at least it's consistent and safe. I'm not sure why we didn't do this before (last famous words)
It seems to work everywhere:
- repo: https://github.com/npmhub/npmhub
- file: https://github.com/npmhub/npmhub/blob/main/package.json
- sub-folder: https://github.com/eslint/eslint/tree/main/packages/eslint-config-eslint
- other branch: https://github.com/npmhub/npmhub/tree/ios
The previous AJAX-related issue persists, so you'd still have to refresh the page. I think #159 will fix that too

Add support for the new GitHub UI

---

source/components/App.svelte
source/components/Box.svelte

- All errors were shown as a static "network error"
- HTTP errors were silenced

Show real error in UI
